#!/usr/bin/env python3
import argparse
from pathlib import Path

import regex


PINNED_REGEX_VERSION = "2026.4.4"
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "Sources/SwiftGigaTokenCore/UnicodeClassTable.swift"


def ranges_for(pattern: regex.Pattern[str]) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    start: int | None = None
    previous = 0
    for scalar in range(0x110000):
        matches = pattern.fullmatch(chr(scalar)) is not None
        if matches and start is None:
            start = scalar
        elif not matches and start is not None:
            result.append((start, previous))
            start = None
        previous = scalar
    if start is not None:
        result.append((start, 0x10FFFF))
    return result


def swift_array(name: str, swift_type: str, values: list[int]) -> str:
    lines: list[str] = []
    current = "    "
    for value in values:
        token = f"{value},"
        if len(current) + len(token) + 1 > 100:
            lines.append(current.rstrip())
            current = "    "
        current += token + " "
    if current.strip():
        lines.append(current.rstrip())
    return (
        f"  private static let {name}: [{swift_type}] = [\n"
        + "\n".join(lines)
        + "\n  ]"
    )


def packed_class_pages(
    letter: list[tuple[int, int]],
    number: list[tuple[int, int]],
    whitespace: list[tuple[int, int]],
) -> tuple[list[int], list[int]]:
    classes = bytearray([3]) * 0x110000
    for ranges, value in [(letter, 0), (number, 1), (whitespace, 2)]:
        for lower, upper in ranges:
            classes[lower : upper + 1] = bytes([value]) * (upper - lower + 1)

    indices: list[int] = []
    unique_pages: list[bytes] = []
    page_ids: dict[bytes, int] = {}
    for page_start in range(0, len(classes), 256):
        source = classes[page_start : page_start + 256]
        packed = bytes(
            source[index]
            | (source[index + 1] << 2)
            | (source[index + 2] << 4)
            | (source[index + 3] << 6)
            for index in range(0, 256, 4)
        )
        page_id = page_ids.get(packed)
        if page_id is None:
            page_id = len(unique_pages)
            page_ids[packed] = page_id
            unique_pages.append(packed)
        indices.append(page_id)
    return indices, [value for page in unique_pages for value in page]


def generated_source() -> str:
    if regex.__version__ != PINNED_REGEX_VERSION:
        raise RuntimeError(
            f"regex {PINNED_REGEX_VERSION} is required, found {regex.__version__}"
        )
    letter = ranges_for(regex.compile(r"\p{Letter}"))
    number = ranges_for(regex.compile(r"\p{Number}"))
    whitespace = ranges_for(regex.compile(r"\p{White_Space}"))
    page_indices, page_data = packed_class_pages(letter, number, whitespace)
    arrays = "\n\n".join(
        [
            swift_array("pageIndices", "UInt16", page_indices),
            swift_array("pageData", "UInt8", page_data),
        ]
    )
    return f"""// Generated by Scripts/generate-unicode-class-table.py using regex {PINNED_REGEX_VERSION}.
// Do not edit by hand. Regenerate and run this script with --check.
enum UnicodeClassTable {{
{arrays}

  @inline(__always)
  static func classify(_ scalar: UInt32) -> CharacterClass {{
    let page = Int(pageIndices[Int(scalar >> 8)])
    let packed = pageData[page * 64 + Int((scalar & 0xFF) >> 2)]
    switch (packed >> UInt8((scalar & 3) << 1)) & 3 {{
    case 0: return .letter
    case 1: return .number
    case 2: return .whitespace
    default: return .other
    }}
  }}
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    source = generated_source()
    if arguments.check:
        if OUTPUT.read_text() != source:
            raise SystemExit(f"Generated source is stale: {OUTPUT}")
        print(f"unicode-table: verified {OUTPUT}")
        return
    OUTPUT.write_text(source)
    print(f"unicode-table: wrote {OUTPUT}")


if __name__ == "__main__":
    main()
